# Advance Operations with Business Example


In [24]:
import numpy as np 
import matplotlib.pyplot as plt

## Data Strucuture

### [Restaurant_id, 2021, 2022, 2023, 2024]

In [ ]:
sales_data=np.array([
    [1, 1000, 1200, 1300, 1400], #Restaurnat 1
    [2, 1500, 1600, 1700, 1800], #Restaurnat 2
    [3, 2000, 2100, 2200, 2300], #Restaurnat 3
    [4, 2500, 2600, 2700, 2800], #Restaurnat 4
    [5, 3000, 3100, 3200, 3300] #Restaurnat 5
])
print("==== Sales Analysis Begins ====")

==== Sales Analysis Begins ====


In [7]:
print("Data Shape = ",sales_data.shape)

Data Shape =  (5, 5)


In [10]:
print("First 3 data = \n",sales_data[:3])

First 3 data = 
 [[   1 1000 1200 1300 1400]
 [   2 1500 1600 1700 1800]
 [   3 2000 2100 2200 2300]]


In [12]:
print("Last 2 data = \n",sales_data[3:])

Last 2 data = 
 [[   4 2500 2600 2700 2800]
 [   5 3000 3100 3200 3300]]


### Total sales per year

In [19]:
print("Sales per year = ",np.sum(sales_data[:, 1:], axis=0))

Sales per year =  [10000 10600 11100 11600]


### Minimum sales per restaurant

In [22]:
min_sale = np.min(sales_data[:, 1:], axis=0)
print("Minimum sales per year each restaurant respectively = ", min_sale)

Minimum sales per year each restaurant respectively =  [1000 1200 1300 1400]


### Average sales per restaurant

In [23]:
avg=np.mean(sales_data[1:,1:], axis=0)
print("Average sales per year each restaurant respectively = ", avg)

Average sales per year each restaurant respectively =  [2250. 2350. 2450. 2550.]
